name: CI Pipeline (Simplified)

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  NODE_VERSION: '18'

jobs:
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build Next.js application
        run: npm run build:ci
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'http://localhost:54321' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder' }}

      - name: Check migration files exist
        run: |
          if [ -z "$(ls -A supabase/migrations/*.sql 2>/dev/null)" ]; then
            echo "❌ No migration files found in supabase/migrations/"
            exit 1
          fi
          echo "✅ Migration files found"
          ls -la supabase/migrations/*.sql